### ISSUE TITLE
Quick Summon feature currently not working

### ISSUE THREAD

**Issue by ParadoxJoy** [DrSalzstreuer/CK-ModSDK#17]
I have 4 friends with the mod installed and last week it was working when you press x it would search inv for summon or use the hotbar one. but currently none of us can quick summon.

**Comment by ParadoxJoy** [comment]
Update sorry for ticket. but it seems to only with the Bat summon. not the others

**Comment by DrSalzstreuer** [comment]
Will look into it, thanks!

**Comment by DrSalzstreuer** [comment]
Please updated to the latest version by opening the mod browser in-game, then restart the game and test again, please.
